development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:p32581588e2d3891d7ebc862565447f214bb2a8c0f0e9ed6631d74064ea1a0974@ec2-3-218-111-152.compute-1.amazonaws.com:23629
  channel_prefix: message_me_production
